version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 4
    target-branch: "main"
    groups:
      all-cargo-updates:
        patterns:
          - "*"
